name: Build for windows

on:
  push:
    branches:
      - CI-TEST
  pull_request:
    branches:
      - CI-TEST

jobs:
  Building:
    runs-on: [windows-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Install Qt
        uses: ouuan/install-qt-action@v2.3.1
        with:
          arch: win64_mingw73
      - name: Install the SFML.
        run: |
           Invoke-WebRequest -Uri https://www.sfml-dev.org/files/SFML-2.5.1-windows-gcc-7.3.0-mingw-64-bit.zip -OutFile sfml.zip
           Expand-Archive sfml.zip -DestinationPath . -Force
           Move-Item -Path SFML-2.5.1 -Destination build
      - name: Build Makefile with CMake
        run: |
          Set-Location build
          cmake .. -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" -DGITBUILD=true
      - name: Build with Makefile
        run: |
          mingw32-make -C build comsquare
      - name: Clean up
        run: |
          Set-Location build
          Remove-Item -Recurse -Path * -Exclude comsquare.exe,bin,bin/*
      - name: Copy shared libs
        run: |
          Copy-Item -Path build\bin\*.dll -Destination build
          Copy-Item -Path 'C:\Program Files\Git\mingw64\bin\*.dll' -Destination build
      - name: Archive production artifact
        uses: actions/upload-artifact@v1
        with:
          name: comsquare-Windows
          path: build/
